
source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'json'
gem 'rest-client'
gem 'tty-table'
gem 'tty-prompt'
gem 'colorize'
gem 'tty-font'
gem 'pastel'
